apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-cipherchat
  labels:
    app: frontend-cipherchat
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-cipherchat
  template:
    metadata:
      labels:
        app: frontend-cipherchat
    spec:
      containers:
      - name: frontend-cipherchat
        image: ijaymane/front-cipherchat:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80 # Nginx كيكونيكطي ف البورط 80 أوتوماتيكيا
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: frontend-cipherchat
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081

